spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host:
    port:
    password:
server:
  context-path: /sell

wechat:
  mpAppId: wx22354f42c27a3f73
  mpAppSecret: dfa7bf085dac32411691cf4cc19bbe3a
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl:

projectUrl:
  wechatMpAuthorize:
  wechatOpenAuthorize:
  sell: