spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password:
server:
  context-path: /sell

wechat:
  mpAppId: wx22354f42c27a3f73
  mpAppSecret: dfa7bf085dac32411691cf4cc19bbe3a
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
  templateId:
    orderStatus:

projectUrl:
  wechatMpAuthorize: http://127.0.0.1
  wechatOpenAuthorize: http://127.0.0.1
  sell: http://127.0.0.1